# Generated by Django 5.2.10 on 2026-02-02 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='base_delivery_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='delivery_scope',
            field=models.CharField(choices=[('ALL_INDIA', 'All India'), ('STATE_ONLY', 'Only Selected States'), ('STATE_EXCEPT', 'All Except Selected States'), ('PINCODE_ONLY', 'Only Selected Pincodes'), ('PINCODE_EXCEPT', 'All Except Selected Pincodes')], default='ALL_INDIA', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='delivery_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.productvariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product_variant', 'order')},
            },
        ),
    ]
