# Generated by Django 5.2.10 on 2026-02-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant_base_delivery_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='review',
            new_name='comment',
        ),
    ]
