# Generated by Django 5.2.10 on 2026-02-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_review_productreview_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_video',
            field=models.FileField(blank=True, null=True, upload_to='brand_videos/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
    ]
