# Generated by Django 5.2.10 on 2026-02-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand_brand_video_brand_header_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_fashion_header',
            field=models.BooleanField(default=False),
        ),
    ]
