# Generated by Django 5.2.10 on 2026-02-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_show_in_fashion_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='footer_brands/'),
        ),
    ]
