# Generated by Django 5.2.10 on 2026-02-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
